# ./docker-compose.yml
services:
  identity-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432" # Porta diferente para não conflitar com outros DBs